image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - Compile
 
maven-jar-compile:
   image: maven:3-jdk-8
   stage: Compile
   script: "mvn package -B"
   artifacts:
     paths:
       - target/*.jar