image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - Compile
  - Build
  - Test
  - Package
  - Staging_QA
  - Staging_PROD
 
maven-jar-compile:
   image: maven:3-jdk-8
   stage: Compile
   script: "mvn package -B"
   artifacts:
     paths:
       - target/*.jar

docker-build:
   stage: Build
   script:
   - docker build -t "$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG" .
   - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
   - docker push "$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG"

 codequality:
   image: docker:stable
   stage: Test
   variables:
     DOCKER_DRIVER: overlay2
   allow_failure: true
   services:
     - docker:stable-dind
   script:
     - setup_docker
     - codeclimate
   artifacts:
     paths: [codeclimate.json]

dependency_scanning:
   image: docker:stable
   stage: Test
   variables:
     DOCKER_DRIVER: overlay2
   allow_failure: true
   services:
     - docker:stable-dind
   script:
     - setup_docker
     - dependency_scanning
   artifacts:
     paths: [gl-dependency-scanning-report.json]