image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - Compile
  - Build
 
maven-jar-compile:
   image: maven:3-jdk-8
   stage: Compile
   script: "mvn package -B"
   artifacts:
     paths:
       - target/*.jar

docker-build:
   stage: Build
   script:
   - docker build -t "$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG" .
   - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
   - docker push "$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG"

 
      